apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

patches:
- path: manager_config_patch.yaml

images:
- name: controller
  newName: crmirror.lcpu.dev/rocm/gpu-operator
  newTag: dev

configurations:
- kustomizeconfig.yaml
